# Generated by Django 4.0.2 on 2023-09-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/bg0.png', null=True, upload_to='media'),
        ),
    ]
