# Generated by Django 5.1.2 on 2024-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaCalls',
        ),
        migrations.RemoveField(
            model_name='mpesacallbacks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesacallbacks',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mpesacallbacks',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpesacallbacks',
            name='content',
            field=models.JSONField(),
        ),
    ]
