# Generated by Django 4.2.5 on 2023-09-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_plan',
            old_name='user',
            new_name='client',
        ),
    ]
