# Generated by Django 4.2.5 on 2023-09-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_my_plan_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_plan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
