# Generated by Django 4.0.2 on 2023-08-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField()),
            ],
        ),
    ]
