# Generated by Django 5.0.1 on 2024-01-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_notification_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='client',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
    ]
