# Generated by Django 5.1.2 on 2024-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_mpesacalls_remove_mpesacallbacks_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbacks',
            name='callback_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
