# Generated by Django 5.1.2 on 2024-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mpesacallbacks_callback_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.CharField(max_length=14)),
                ('account_reference', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('payer_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
    ]
